### ISSUE TITLE
Optimisation needed

### ISSUE THREAD

**Issue by gojakuch** [JuliaHEP/JetReconstruction.jl#15]
The current Julia implementation is significantly slower than C++ FastJet and I assume we can do better. Here you can see a plot that compares benchmarking results from an older version of this repo, which is already heavily optimised, ("Faster Julia" from about a week ago, showed in dark purple) with the currently used version of the algorithm ("New Faster Julia", in magenta).  C++ FastJet is still way below. I did not include compilation time and used BenchmarkTools.jl for benchmarking. For the Julia approaches I've plotted the entire range of runtimes as well as the median (it's very close to the lower bound).

![image](https://user-images.githubusercontent.com/65173069/189209485-6c4ab306-4a2b-4735-bc6a-4194f2629ef7.png)

I cannot think of any other methods to optimise the code for now. The latest updates have already been inspired mostly by @Moelf 's suggestions (i.e. using `@inbounds @simd for`, `Base.@propagate_inbounds`, etc). In case anyone is able to spot other issues or knows ways to optimise the code with more or less native Julia methods, please let me know.

P.S. Profiling shows that most of the time we spend in the two following blocks of code:
```julia
...
## src/Algo.jl @ line 105 
# initialize _nn
@simd for i in 1:N
    _upd_nn_crosscheck!(i, 1, i-1, _eta, _phi, _R2, _nndist, _nn)
end
...
```
```julia
...
## src/Algo.jl @ line 165 
# update nearest neighbours step
@inbounds @simd for k in 1:N
    _upd_nn_step!(i, j, k, N, Nn, _kt2, _eta, _phi, _R2, _nndist, _nn, _nndij)
end
...
```

**Comment by Moelf** [comment]
a few questions:
- are the results close to each other?
- does C++ use the same precision?
- does C++ use fast math?
- single threaded?
- is there any BLAS/MKL difference involved?

**Comment by jstrube** [comment]
Is there a different algorithmic complexity between C++ and Julia? The FastJet authors worked hard to try and beat the naive N^3 scaling. I don't know where they arrived at, but I seem to remember their paper talks about that. Would be interesting to see if there are more algorithmic tricks one could use.

**Comment by gojakuch** [comment]
> * are the results close to each other?
almost identical
> * does C++ use the same precision?
both C++ and Julia use 64-bit floats there
> * does C++ use fast math?
not sure
> * single threaded?
yes
> * is there any BLAS/MKL difference involved?
not sure

**Comment by gojakuch** [comment]
> Is there a different algorithmic complexity between C++ and Julia? The FastJet authors worked hard to try and beat the naive N^3 scaling. I don't know where they arrived at, but I seem to remember their paper talks about that. Would be interesting to see if there are more algorithmic tricks one could use.

FastJet uses different strategies depending on the number of input points. What we have in Julia now is one of them re-implemented in a Julian way, so algorithmic complexity (for what I showed on the plot) should be the same.
