### ISSUE TITLE
Plotting support

### ISSUE THREAD

**Issue by graeme-a-stewart** [JuliaHEP/JetReconstruction.jl#43]
Based on the new `ClusterSequence` return type, develop plotting routines to visualise the output of the reconstruction

**Comment by gojakuch** [comment]
hi, so is this issue on the branch main or on the cluster-sequence?

**Comment by graeme-a-stewart** [comment]
Hi @gojakuch. The `cluster-sequence` branch was rebased and merged, so it shouldn't have been hanging around - I have deleted it now.

My current development branch is `inclusive-jets`, which I have pushed to GitHb now, so you can see it. There are some changes in the pipeline to [`ClusterSequence.jl`](https://github.com/JuliaHEP/JetReconstruction.jl/blob/exclusive-jets/src/ClusterSequence.jl), adding algorithm and strategy information - plus the algorithm and strategy are encoded now as named enums (with the `EmumX` package). However, I don't think that changes anything w.r.t. the core visualisation task, which would use `ClusterSequence.jets` and `ClusterSequence.history`.

Summary: it should be ok to attack this on `main`!

My hope is to merge the `inclusive-jets` branch soon - it's in mostly working, but there are some differences with FastJet for the $d_{ij}$ cuts that I need to understand before it's really good to go (the $n_{jets}$ cut seems to work just fine). That said, next week I am at a workshop all week, so time is pretty limited for the rest of May 😅.

**Comment by graeme-a-stewart** [comment]
Thanks so much @gojakuch and to @Moelf for helping! (I was completely overwhelmed last week at the HSF workshop)
