### ISSUE TITLE
use existing Lorentz Vector package

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/JetReconstruction.jl#5]
https://github.com/JuliaHEP/LorentzVectorHEP.jl instead of https://github.com/gojakuch/JetReconstruction.jl/blob/main/src/Particle.jl ?

**Comment by graeme-a-stewart** [comment]
Hi @Moelf - yes, this is the plan as we prepare the package for a public release! I would also like the HepMC3 reader we have to return LorentzVectorHEP objects.
