### ISSUE TITLE
Fix documentation versions

### ISSUE THREAD

**Issue by graeme-a-stewart** [JuliaHEP/JetReconstruction.jl#78]
At the moment we don't have versioned documentation correctly produced - we only get the `main` branch, i.e., `dev` documentation.

@Moelf pointed to [Lux.jl](https://lux.csail.mit.edu/stable/) as an example that has managed to get this correct - it's probably a minor configuration issue.

However, documentation for older releases may need to be created by hand.

**Comment by graeme-a-stewart** [comment]
I am having real issues with Vitepress in that it seems to be impossible to get a working preview of the site. The suggestions in https://luxdl.github.io/DocumenterVitepress.jl/v0.1.3/getting_started#Preview-Documentation-Development-Instantly are complicated, require changes to be done, then undone and, worst of all, *they didn't even work for me*.

So for now I have removed the `DocumenterVitepress` setup via #80.

**Comment by graeme-a-stewart** [comment]
Which is a pain when certain things aren't working... I want to get the versioning sorted, then return to reenabling the fancy stuff

**Comment by graeme-a-stewart** [comment]
It is actually really important to have a good local preview when working on documentation improvements

**Comment by Moelf** [comment]
I have it working locally, but i remember it was a bit pain to set up

**Comment by graeme-a-stewart** [comment]
Yeah, too fiddly for today ;)

I have now fixed the documentation and recreated manually all of the past versions in the `gh-pages` branch. But I will keep this issue open until the next tag is made to check that Documenter.jl does the right thing with the next version.

**Comment by graeme-a-stewart** [comment]
Creating the next tag, `v0.4.2` did not result in a documenter run. I can't see anything wrong with the GH action, which is set to run on tag events (and looks just like many of the other actions in repositories with `Documenter.jl`).

https://github.com/JuliaHEP/JetReconstruction.jl/blob/9bbd8b8b0e52097030d73e2e5776ab4e8f1bac49/.github/workflows/Documentation.yml#L3-L8

Either the document action is not being triggered, or it's triggered and is failing.

**Comment by Moelf** [comment]
I'm pretty sure you need
```
DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```

**Comment by graeme-a-stewart** [comment]
I also noticed that late last night! 🤞 it solves the issue.

https://github.com/JuliaHEP/JetReconstruction.jl/commit/28d7f0d2e045140e99289fc06f5b87ec7651d482

**Comment by Moelf** [comment]
![image](https://github.com/user-attachments/assets/fc6d732d-9c6a-4bac-97fa-9125ebcc86b6)


I don't see we have added `DOCUMENTER_KEY`
